import { Paths } from "app/constants/paths";

export const TotemsData = {
  FOX: {
    id: 1,
    name: "Fox",
    path: Paths.foxPool,
    icon: "fox-white.svg",
    color: "#FF6600",
    message: "4 days",
    maxPoolSize: 120000,
    days: 4,
    btcReward: 0.1,
    btcUsdPrize: 125,
    totemReward: 2000,
    collaborateBonus: 0.2,
    collaborateRange: 50,
    stakingReward: 1,
    lockTime: 259200,
  },
  WOLF: {
    id: 2,
    name: "Wolf",
    icon: "wolf-white.svg",
    iconMobile: "wolf-white.svg",
    path: Paths.wolfPool,
    colorMobile: "#C4DBE0",
    color: "#455461",
    message: "14 days",
    maxPoolSize: 250000,
    days: 14,
    btcReward: 0.125,
    totemReward: 6000,
    btcUsdPrize: 1000,
    collaborateBonus: 0.25,
    stakingReward: 0.2,
    collaborateRange: 100,
    lockTime: 864000,
  },
  OWL: {
    id: 3,
    name: "Owl",
    path: Paths.owlPool,
    iconMobile: "owl-white.svg",
    icon: "owl-white.svg",
    colorMobile: "#C4DBE0",
    color: "#739BA2",
    message: "36 days",
    maxPoolSize: 300000,
    days: 36,
    btcReward: 0.15,
    totemReward: 8000,
    btcUsdPrize: 3000,
    collaborateBonus: 0.2,
    collaborateRange: 100,
    stakingReward: 0.75,
    lockTime: 2592000,
  },
  // ALL: {
  //   id: 4,
  //   name: "Latest",
  //   path: Paths.allPool,
  //   iconMobile: "",
  //   icon: "",
  //   colorMobile: "#C4DBE0",
  //   color: "#739BA2",
  //   message: "Latest",
  //   days: 8, // TODO: what is days value for ALL ?
  //   maxPoolSize: 125000,
  //   btcReward: 0.15,
  //   totemReward: 6500,
  //   btcUsdPrize: 1000,
  //   collaborateBonus: 0.35,
  //   collaborateRange: 50,
  //   stakingReward: 0.75,
  //   lockTime: 0,
  // },

  USER: {
    name: "My Account",
    path: Paths.user,
    iconMobile: "account-black.svg",
    icon: "account-white.svg",
    color: "#C4DBE0",
    colorMobile: "#739BA2",
    message: "Account",
  },
  UNISWAP: {
    name: "Uniswap",
    path: Paths.uniswap,
    icon: "uniswap-black.svg",
    colorMobile: "#739BA2",
    color: "#C4DBE0",
    message: "Uniswap",
  },
  GATE: {
    name: "Gate.io",
    path: Paths.gate,
    icon: "uniswap-black.svg",
    colorMobile: "#739BA2",
    color: "#C4DBE0",
    message: "Gate",
  },
  PANCAKE_SWAP: {
    name: "Pancake Swap",
    path: Paths.pancakeSwap,
    icon: "uniswap-black.svg",
    colorMobile: "#739BA2",
    color: "#C4DBE0",
    message: "PancakeSwap",
  },
  DUCK_BRIDGE: {
    name: "Duck Bridge",
    path: Paths.duckBridge,
    icon: "uniswap-black.svg",
    colorMobile: "#739BA2",
    color: "#C4DBE0",
    message: "PancakeSwap",
  },
  FAQS: {
    name: "FAQS",
    path: Paths.faqs,
    colorMobile: "#ffffff",
    color: "#ffffff",
    message: "FAQs",
  },
  SUPPORT: {
    name: "Support",
    path: Paths.support,
    colorMobile: "#ffffff",
    color: "#ffffff",
    message: "Support",
  },
};
