/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface BTCDistributorInterface extends ethers.utils.Interface {
  functions: {
    "getEstimatedBTCForUSD(uint256)": FunctionFragment;
    "getPathForUSDToBTC()": FunctionFragment;
    "getswapRouter()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getEstimatedBTCForUSD",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPathForUSDToBTC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getswapRouter",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getEstimatedBTCForUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPathForUSDToBTC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getswapRouter",
    data: BytesLike
  ): Result;

  events: {
    "DistributedBTC(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DistributedBTC"): EventFragment;
}

export class BTCDistributor extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BTCDistributorInterface;

  functions: {
    getEstimatedBTCForUSD(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getEstimatedBTCForUSD(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPathForUSDToBTC(overrides?: CallOverrides): Promise<[string[]]>;

    "getPathForUSDToBTC()"(overrides?: CallOverrides): Promise<[string[]]>;

    getswapRouter(overrides?: CallOverrides): Promise<[string]>;

    "getswapRouter()"(overrides?: CallOverrides): Promise<[string]>;
  };

  getEstimatedBTCForUSD(
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getEstimatedBTCForUSD(uint256)"(
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPathForUSDToBTC(overrides?: CallOverrides): Promise<string[]>;

  "getPathForUSDToBTC()"(overrides?: CallOverrides): Promise<string[]>;

  getswapRouter(overrides?: CallOverrides): Promise<string>;

  "getswapRouter()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getEstimatedBTCForUSD(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getEstimatedBTCForUSD(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPathForUSDToBTC(overrides?: CallOverrides): Promise<string[]>;

    "getPathForUSDToBTC()"(overrides?: CallOverrides): Promise<string[]>;

    getswapRouter(overrides?: CallOverrides): Promise<string>;

    "getswapRouter()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    DistributedBTC(
      to: string | null,
      amount: null
    ): TypedEventFilter<[string, BigNumber], { to: string; amount: BigNumber }>;
  };

  estimateGas: {
    getEstimatedBTCForUSD(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getEstimatedBTCForUSD(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPathForUSDToBTC(overrides?: CallOverrides): Promise<BigNumber>;

    "getPathForUSDToBTC()"(overrides?: CallOverrides): Promise<BigNumber>;

    getswapRouter(overrides?: CallOverrides): Promise<BigNumber>;

    "getswapRouter()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getEstimatedBTCForUSD(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getEstimatedBTCForUSD(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPathForUSDToBTC(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPathForUSDToBTC()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getswapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getswapRouter()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
