/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface RewarderInterface extends ethers.utils.Interface {
  functions: {
    "addRewarder(address)": FunctionFragment;
    "isRewarder(address)": FunctionFragment;
    "renounceRewarder()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addRewarder", values: [string]): string;
  encodeFunctionData(functionFragment: "isRewarder", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceRewarder",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addRewarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isRewarder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRewarder",
    data: BytesLike
  ): Result;

  events: {
    "RewarderAdded(address)": EventFragment;
    "RewarderRemoved(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RewarderAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewarderRemoved"): EventFragment;
}

export class Rewarder extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RewarderInterface;

  functions: {
    addRewarder(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "addRewarder(address)"(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isRewarder(account: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isRewarder(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    renounceRewarder(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "renounceRewarder()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addRewarder(
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "addRewarder(address)"(
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isRewarder(account: string, overrides?: CallOverrides): Promise<boolean>;

  "isRewarder(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  renounceRewarder(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "renounceRewarder()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addRewarder(account: string, overrides?: CallOverrides): Promise<void>;

    "addRewarder(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isRewarder(account: string, overrides?: CallOverrides): Promise<boolean>;

    "isRewarder(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    renounceRewarder(overrides?: CallOverrides): Promise<void>;

    "renounceRewarder()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    RewarderAdded(
      account: string | null
    ): TypedEventFilter<[string], { account: string }>;

    RewarderRemoved(
      account: string | null
    ): TypedEventFilter<[string], { account: string }>;
  };

  estimateGas: {
    addRewarder(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "addRewarder(address)"(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isRewarder(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isRewarder(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceRewarder(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "renounceRewarder()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addRewarder(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "addRewarder(address)"(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isRewarder(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isRewarder(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceRewarder(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "renounceRewarder()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
